# Generated by Django 4.1.6 on 2023-02-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_invoice_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
