# Generated by Django 4.1.6 on 2023-02-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0003_invoice_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='until',
            field=models.DateField(null=True),
        ),
    ]
