# Generated by Django 4.1.6 on 2023-02-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0004_alter_invoice_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='until',
            field=models.DateTimeField(null=True),
        ),
    ]
